version: '3.9'

services:
  wandb:
    image: wandb/local
    ports:
      - "5441:8080"
    volumes:
      - type: bind
        source: /speedy/eduong/wandb
        target: /vol
    environment:
      - HOST=http://localhost:5441
